name: Build & Sign Android (Gradle signing)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # all commands run inside the android/ subfolder
    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Locate Android build-tools
        id: tools
        run: |
          set -e
          echo "Installed build-tools:"
          ls -1 "$ANDROID_HOME/build-tools" | sort -V
          BT="$ANDROID_HOME/build-tools/$(ls -1 "$ANDROID_HOME/build-tools" | sort -V | tail -n1)"
          echo "Using: $BT"
          echo "BUILD_TOOLS=$BT" >> $GITHUB_ENV

      # Put a keystore where Gradle expects it, and set env vars Gradle reads
      - name: Prepare keystore at android/release.keystore
        shell: bash
        run: |
          set -e
          # Ensure we are inside the android/ folder
          pwd

          if [ -n "$]()
